### ISSUE TITLE
obj to MeshLab

### ISSUE THREAD

**Issue by rude64** [mike-gill/qgis2sketchfab#1]
Hi Mike,
thanks very much for sharing your qgis2sketchfab! But, somehow it doesn't work quite nice with me. When importing the .obj file into MeshLab I got an error, like this:
"While opening: '/filename_uv.obj'
Error encountered while loading file:
"/filename_uv.obj"
Error details: Some materials definitions were not found, a default white material is used where no material was available"

So, I don't get the .png on top of/meshed with my material. I followed your steps twice, but still the same. Any thoughts?

Cheers,
Ruud

**Comment by mike-gill** [comment]
Hi Ruud, do you have any spaces in any filenames:  https://sourceforge.net/p/meshlab/bugs/406/

Mike

**Comment by rude64** [comment]
Hi Mike, the spaces weren't a problem. I forgot to save all files in one folder :-|
Now it works all fine. Check the results: https://skfb.ly/6syBT
Thanks again very much!
Ruud
